import { MWForm } from './models';

export const DEMO_FORM: MWForm = {
  name: 'Complete Survey Demo',
  description:
    'This demo showcases all 18 question types available in Angular Surveys. Experience the full range of input options!',
  pages: [
    {
      id: 'page-1',
      number: 1,
      name: 'Text Input Questions',
      description: 'Various text-based input types',
      pageFlow: { nextPage: true },
      elements: [
        {
          id: 'q1',
          orderNo: 1,
          type: 'question',
          question: {
            id: 'name',
            text: 'What is your full name?',
            type: 'text',
            required: true,
            placeholder: 'Enter your full name',
          },
        },
        {
          id: 'q2',
          orderNo: 2,
          type: 'question',
          question: {
            id: 'email',
            text: 'What is your email address?',
            type: 'email',
            required: true,
            placeholder: 'example@email.com',
          },
        },
        {
          id: 'q3',
          orderNo: 3,
          type: 'question',
          question: {
            id: 'phone',
            text: 'What is your phone number?',
            type: 'phone',
            required: false,
            placeholder: '+1 (555) 123-4567',
          },
        },
        {
          id: 'q4',
          orderNo: 4,
          type: 'question',
          question: {
            id: 'website',
            text: 'Your website or portfolio URL',
            type: 'url',
            required: false,
            placeholder: 'https://yourwebsite.com',
          },
        },
        {
          id: 'q5',
          orderNo: 5,
          type: 'question',
          question: {
            id: 'bio',
            text: 'Tell us about yourself',
            type: 'textarea',
            required: false,
            placeholder: 'Share a brief introduction...',
          },
        },
      ],
      namedPage: true,
    },
    {
      id: 'page-2',
      number: 2,
      name: 'Product Experience',
      description: 'Tell us about your experience with our products',
      pageFlow: { nextPage: true },
      elements: [
        {
          id: 'q5',
          orderNo: 1,
          type: 'question',
          question: {
            id: 'product-category',
            text: 'Which product category are you providing feedback on?',
            type: 'select',
            required: true,
            offeredAnswers: [
              { id: 'cat1', orderNo: 1, value: 'Software' },
              { id: 'cat2', orderNo: 2, value: 'Hardware' },
              { id: 'cat3', orderNo: 3, value: 'Services' },
              { id: 'cat4', orderNo: 4, value: 'Support' },
            ],
          },
        },
        {
          id: 'q6',
          orderNo: 2,
          type: 'question',
          question: {
            id: 'satisfaction',
            text: 'How satisfied are you with our product?',
            type: 'radio',
            required: true,
            pageFlowModifier: true,
            offeredAnswers: [
              {
                id: 'sat1',
                orderNo: 1,
                value: 'Very Satisfied',
                pageFlow: { goToPage: 4 },
              },
              {
                id: 'sat2',
                orderNo: 2,
                value: 'Satisfied',
                pageFlow: { goToPage: 4 },
              },
              { id: 'sat3', orderNo: 3, value: 'Neutral' },
              {
                id: 'sat4',
                orderNo: 4,
                value: 'Dissatisfied',
                pageFlow: { goToPage: 3 },
              },
              {
                id: 'sat5',
                orderNo: 5,
                value: 'Very Dissatisfied',
                pageFlow: { goToPage: 3 },
              },
            ],
          },
        },
        {
          id: 'q7',
          orderNo: 3,
          type: 'question',
          question: {
            id: 'features-used',
            text: 'Which features do you use regularly? (Select all that apply)',
            type: 'checkbox',
            required: true,
            offeredAnswers: [
              { id: 'feat1', orderNo: 1, value: 'Dashboard' },
              { id: 'feat2', orderNo: 2, value: 'Analytics' },
              { id: 'feat3', orderNo: 3, value: 'Reporting' },
              { id: 'feat4', orderNo: 4, value: 'Integrations' },
              { id: 'feat5', orderNo: 5, value: 'API Access' },
            ],
            otherAnswer: true,
          },
        },
      ],
      namedPage: true,
    },
    {
      id: 'page-3',
      number: 3,
      name: 'Improvement Feedback',
      description:
        "We're sorry to hear you're not fully satisfied. Please help us understand how we can improve.",
      pageFlow: { nextPage: true, goToPage: 5 },
      elements: [
        {
          id: 'q8',
          orderNo: 1,
          type: 'question',
          question: {
            id: 'issues',
            text: 'What issues have you experienced?',
            type: 'checkbox',
            required: true,
            offeredAnswers: [
              { id: 'issue1', orderNo: 1, value: 'Performance problems' },
              { id: 'issue2', orderNo: 2, value: 'Bugs or errors' },
              { id: 'issue3', orderNo: 3, value: 'Missing features' },
              { id: 'issue4', orderNo: 4, value: 'Difficult to use' },
              { id: 'issue5', orderNo: 5, value: 'Poor documentation' },
            ],
            otherAnswer: true,
          },
        },
        {
          id: 'q9',
          orderNo: 2,
          type: 'question',
          question: {
            id: 'improvement-details',
            text: 'Please describe the issues in detail',
            type: 'textarea',
            required: true,
            placeholder:
              "Tell us more about the problems you've encountered...",
          },
        },
      ],
      namedPage: true,
    },
    {
      id: 'page-4',
      number: 4,
      name: 'Rating & Scale Questions',
      description: 'Please rate various aspects of our product',
      pageFlow: { nextPage: true },
      elements: [
        {
          id: 'q10',
          orderNo: 1,
          type: 'question',
          question: {
            id: 'overall-rating',
            text: 'How would you rate our product overall?',
            type: 'scale',
            required: true,
            scale: {
              min: 1,
              max: 10,
              step: 1,
              minLabel: 'Poor',
              maxLabel: 'Excellent',
            },
          },
        },
        {
          id: 'q11',
          orderNo: 2,
          type: 'question',
          question: {
            id: 'feature-ratings',
            text: 'Please rate the following aspects:',
            type: 'grid',
            required: true,
            grid: {
              cellInputType: 'radio',
              rows: [
                { id: 'row1', orderNo: 1, label: 'Ease of use' },
                { id: 'row2', orderNo: 2, label: 'Performance' },
                { id: 'row3', orderNo: 3, label: 'Design' },
                { id: 'row4', orderNo: 4, label: 'Value for money' },
              ],
              cols: [
                { id: 'col1', orderNo: 1, label: 'Poor' },
                { id: 'col2', orderNo: 2, label: 'Fair' },
                { id: 'col3', orderNo: 3, label: 'Good' },
                { id: 'col4', orderNo: 4, label: 'Excellent' },
              ],
            },
          },
        },
        {
          id: 'q12',
          orderNo: 3,
          type: 'question',
          question: {
            id: 'usage-hours',
            text: 'How many hours per week do you use our product?',
            type: 'number',
            required: true,
            placeholder: 'Enter hours',
            numberConfig: {
              min: 0,
              max: 168,
              step: 1,
              suffix: 'hours',
            },
          },
        },
      ],
      namedPage: true,
    },
    {
      id: 'page-5',
      number: 5,
      name: 'Priorities & Preferences',
      description: 'Help us understand what matters most to you',
      pageFlow: { nextPage: true },
      elements: [
        {
          id: 'q13',
          orderNo: 1,
          type: 'question',
          question: {
            id: 'feature-priority',
            text: 'Rank these features by importance (drag to reorder):',
            type: 'priority',
            required: true,
            priorityList: [
              { id: 'p1', orderNo: 1, value: 'Speed & Performance' },
              { id: 'p2', orderNo: 2, value: 'Security' },
              { id: 'p3', orderNo: 3, value: 'User Interface' },
              { id: 'p4', orderNo: 4, value: 'Customer Support' },
              { id: 'p5', orderNo: 5, value: 'Price' },
            ],
          },
        },
        {
          id: 'q14',
          orderNo: 2,
          type: 'question',
          question: {
            id: 'purchase-date',
            text: 'When did you first start using our product?',
            type: 'date',
            required: true,
          },
        },
        {
          id: 'q15',
          orderNo: 3,
          type: 'question',
          question: {
            id: 'best-contact-time',
            text: 'What is the best time to contact you?',
            type: 'time',
            required: false,
          },
        },
      ],
      namedPage: true,
    },
    {
      id: 'page-6',
      number: 6,
      name: 'Advanced Input Types',
      description: 'Showcasing ratings, NPS, file uploads, and signatures',
      pageFlow: { nextPage: true },
      elements: [
        {
          id: 'q16',
          orderNo: 1,
          type: 'question',
          question: {
            id: 'star-rating',
            text: 'How would you rate your overall experience?',
            type: 'rating',
            required: true,
          },
        },
        {
          id: 'q17',
          orderNo: 2,
          type: 'question',
          question: {
            id: 'nps-score',
            text: 'How likely are you to recommend us to a friend or colleague?',
            type: 'nps',
            required: true,
          },
        },
        {
          id: 'q18',
          orderNo: 3,
          type: 'question',
          question: {
            id: 'file-upload',
            text: 'Upload any supporting documents (optional)',
            type: 'file',
            required: false,
            fileConfig: {
              accept: ['image/*', '.pdf', '.doc', '.docx'],
              maxSize: 5,
              multiple: true,
            },
          },
        },
        {
          id: 'q19',
          orderNo: 4,
          type: 'question',
          question: {
            id: 'signature',
            text: 'Please provide your signature',
            type: 'signature',
            required: false,
          },
        },
      ],
      namedPage: true,
    },
    {
      id: 'page-7',
      number: 7,
      name: 'Final Comments',
      description: "Any additional feedback you'd like to share",
      pageFlow: { nextPage: true },
      elements: [
        {
          id: 'q20',
          orderNo: 1,
          type: 'question',
          question: {
            id: 'recommend',
            text: 'Would you recommend our product to others?',
            type: 'radio',
            required: true,
            offeredAnswers: [
              { id: 'rec1', orderNo: 1, value: 'Definitely yes' },
              { id: 'rec2', orderNo: 2, value: 'Probably yes' },
              { id: 'rec3', orderNo: 3, value: 'Not sure' },
              { id: 'rec4', orderNo: 4, value: 'Probably not' },
              { id: 'rec5', orderNo: 5, value: 'Definitely not' },
            ],
          },
        },
        {
          id: 'q21',
          orderNo: 2,
          type: 'question',
          question: {
            id: 'additional-comments',
            text: 'Any additional comments or suggestions?',
            type: 'textarea',
            required: false,
            placeholder: 'Share any other thoughts you have...',
          },
        },
      ],
      namedPage: true,
    },
  ],
};
